// EVM (Huff) backend code generator — scaffolding stub. See EvmBackend.cs.
using System;
using System.Collections.Generic;
using System.Numerics;
using JetBrains.Annotations;
using Microsoft.BaseTypes;

namespace Microsoft.Dafny.Compilers {

  internal class EvmCodeGenerator : SinglePassCodeGenerator {

    public EvmCodeGenerator(DafnyOptions options, ErrorReporter reporter) : base(options, reporter) { }

    public override IReadOnlySet<Feature> UnsupportedFeatures => new HashSet<Feature> {
      Feature.UnboundedIntegers,
      Feature.RealNumbers,
      Feature.Ordinals,
      Feature.FunctionValues,
      Feature.Iterators,
      Feature.CollectionsOfTraits,
      Feature.Codatatypes,
      Feature.Multisets,
      Feature.MultiDimensionalArrays,
      Feature.MapComprehensions,
      Feature.Traits,
      Feature.LetSuchThatExpressions,
      Feature.MethodSynthesis,
      Feature.ExternalClasses,
      Feature.NewObject,
      Feature.NonSequentializableForallStatements,
      Feature.ArrayLength,
      Feature.MapItems,
      Feature.RunAllTests,
      Feature.IntBoundedPool,
      Feature.ExactBoundedPool,
      Feature.SequenceDisplaysOfCharacters,
      Feature.TypeTests,
      Feature.SubsetTypeTests,
      Feature.Quantifiers,
      Feature.BitvectorRotateFunctions,
      Feature.ForLoops,
      Feature.ContinueStatements,
      Feature.AssignSuchThatWithNonFiniteBounds,
      Feature.SequenceUpdateExpressions,
      Feature.SequenceConstructionsWithNonLambdaInitializers,
      Feature.ExternalConstructors,
      Feature.TupleInitialization,
      Feature.SubtypeConstraintsInQuantifiers,
      Feature.TuplesWiderThan20,
      Feature.ArraysWithMoreThan16Dims,
      Feature.ArrowsWithMoreThan16Arguments,
      Feature.UnicodeChars,
      Feature.ConvertingValuesToStrings,
      Feature.SeparateCompilation,
      Feature.BuiltinsInRuntime,
      Feature.RuntimeCoverageReport,
      Feature.StandardLibraries,
      Feature.StandardLibrariesActionsExterns,
      Feature.NonNativeNewtypes
    };

    public override string ModuleSeparator => "_";

    public override void EmitCallToMain(Method mainMethod, string baseName, ConcreteSyntaxTree callToMainTree) {
      throw new NotImplementedException("EVM backend scaffolding: EmitCallToMain not yet implemented");
    }

    public override string PublicIdProtect(string name) {
      // Huff identifiers are [A-Za-z_][A-Za-z0-9_]*. Replace anything else with "_".
      if (name == null) {
        return null;
      }
      var sb = new System.Text.StringBuilder(name.Length);
      foreach (var c in name) {
        sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
      }
      var s = sb.ToString();
      if (s.Length == 0 || char.IsDigit(s[0])) {
        s = "_" + s;
      }
      return s;
    }

    protected override ConcreteSyntaxTree CreateStaticMain(IClassWriter wr, string argsParameterName) {
      throw new NotImplementedException("EVM backend scaffolding: CreateStaticMain not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateModule(ModuleDefinition module, string moduleName, bool isDefault,
      ModuleDefinition externModule,
      string libraryName /*?*/, Attributes moduleAttributes, ConcreteSyntaxTree wr) {
      // Each Dafny module becomes one Huff source file.
      var safeName = PublicIdProtect(moduleName);
      if (string.IsNullOrEmpty(safeName)) {
        safeName = "_default";
      }
      var file = wr.NewFile($"{safeName}.huff");
      file.WriteLine("/* ============================================================");
      file.WriteLine(" *  Generated by the Dafny EVM (Huff) backend  [experimental]");
      file.WriteLine($" *  Dafny module : {moduleName}");
      file.WriteLine(" * ============================================================ */");
      file.WriteLine();
      return file;
    }

    protected override string GetHelperModuleName() {
      throw new NotImplementedException("EVM backend scaffolding: GetHelperModuleName not yet implemented");
    }

    protected override IClassWriter CreateClass(string moduleName, bool isExtern, string/*?*/ fullPrintName,
      List<TypeParameter> typeParameters, TopLevelDecl cls, List<Type>/*?*/ superClasses, IOrigin tok, ConcreteSyntaxTree wr) {
      // One Dafny class becomes one Huff "contract": storage-slot constants,
      // one macro per method, and a MAIN() dispatcher at the end.
      var name = PublicIdProtect(cls.Name);
      wr.WriteLine($"/* --------- Contract: {name} --------- */");
      wr.WriteLine();
      return new EvmClassWriter(this, name, wr);
    }

    protected override IClassWriter CreateTrait(string name, bool isExtern, List<TypeParameter> typeParameters /*?*/,
      TraitDecl trait, List<Type> superClasses /*?*/, IOrigin tok, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: CreateTrait not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateIterator(IteratorDecl iter, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: CreateIterator not yet implemented");
    }

    protected override IClassWriter/*?*/ DeclareDatatype(DatatypeDecl dt, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareDatatype not yet implemented");
    }

    protected override IClassWriter DeclareNewtype(NewtypeDecl nt, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareNewtype not yet implemented");
    }

    protected override void DeclareSubsetType(SubsetTypeDecl sst, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareSubsetType not yet implemented");
    }

    protected override void GetNativeInfo(NativeType.Selection sel, out string name, out string literalSuffix, out bool needsCastAfterArithmetic) {
      name = default;
      literalSuffix = default;
      needsCastAfterArithmetic = default;
      throw new NotImplementedException("EVM backend scaffolding: GetNativeInfo not yet implemented");
    }

    protected override string TypeDescriptor(Type type, ConcreteSyntaxTree wr, IOrigin tok) {
      throw new NotImplementedException("EVM backend scaffolding: TypeDescriptor not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitTailCallStructure(MemberDecl member, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitTailCallStructure not yet implemented");
    }

    protected override void EmitJumpToTailCallStart(ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitJumpToTailCallStart not yet implemented");
    }

    internal override string TypeName(Type type, ConcreteSyntaxTree wr, IOrigin tok, MemberDecl/*?*/ member = null) {
      // Every Dafny value lives on the EVM stack as a 256-bit word. The Huff
      // backend does not emit static type annotations, so a uniform placeholder
      // is enough for diagnostic strings.
      return "uint256";
    }

    protected override string TypeInitializationValue(Type type, ConcreteSyntaxTree wr, IOrigin tok,
      bool usePlaceboValue, bool constructTypeParameterDefaultsFromTypeDescriptors) {
      // All EVM/Huff values default to a 256-bit zero word.
      return "0";
    }

    protected override string TypeName_UDT(string fullCompileName, List<TypeParameter.TPVariance> variance,
      List<Type> typeArgs, ConcreteSyntaxTree wr, IOrigin tok, bool omitTypeArguments) {
      // Huff has no user-defined types; the name is only used in comments.
      return PublicIdProtect(fullCompileName);
    }

    internal override string/*?*/ TypeName_Companion(Type type, ConcreteSyntaxTree wr, IOrigin tok, MemberDecl/*?*/ member) {
      // No companion types in Huff output.
      return null;
    }

    protected override bool DeclareFormal(string prefix, string name, Type type, IOrigin tok, bool isInParam, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareFormal not yet implemented");
    }

    protected override void DeclareLocalVar(string name, Type/*?*/ type, IOrigin /*?*/ tok, bool leaveRoomForRhs, string/*?*/ rhs,
      ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareLocalVar not yet implemented");
    }

    protected override ConcreteSyntaxTree DeclareLocalVar(string name, Type/*?*/ type, IOrigin/*?*/ tok, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareLocalVar not yet implemented");
    }

    protected override void DeclareLocalOutVar(string name, Type type, IOrigin tok, string rhs, bool useReturnStyleOuts,
      ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: DeclareLocalOutVar not yet implemented");
    }

    protected override void EmitActualTypeArgs(List<Type> typeArgs, IOrigin tok, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitActualTypeArgs not yet implemented");
    }

    protected override void EmitPrintStmt(ConcreteSyntaxTree wr, Expression arg) {
      throw new NotImplementedException("EVM backend scaffolding: EmitPrintStmt not yet implemented");
    }

    protected override void EmitReturn(List<Formal> outParams, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitReturn not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateLabeledCode(string label, bool createContinueLabel, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: CreateLabeledCode not yet implemented");
    }

    protected override void EmitBreak(string/*?*/ label, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitBreak not yet implemented");
    }

    protected override void EmitContinue(string label, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitContinue not yet implemented");
    }

    protected override void EmitYield(ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitYield not yet implemented");
    }

    protected override void EmitAbsurd(string/*?*/ message, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitAbsurd not yet implemented");
    }

    protected override void EmitHalt(IOrigin tok, Expression /*?*/ messageExpr, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitHalt not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitForStmt(IOrigin tok, IVariable loopIndex, bool goingUp,
      string/*?*/ endVarName,
      List<Statement> body, List<Label> labels, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitForStmt not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateForLoop(string indexVar, Action<ConcreteSyntaxTree> bound,
      ConcreteSyntaxTree wr, string start = null) {
      throw new NotImplementedException("EVM backend scaffolding: CreateForLoop not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateDoublingForLoop(string indexVar, int start, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: CreateDoublingForLoop not yet implemented");
    }

    protected override void EmitIncrementVar(string varName, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIncrementVar not yet implemented");
    }

    protected override void EmitDecrementVar(string varName, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitDecrementVar not yet implemented");
    }

    protected override string GetQuantifierName(string bvType) {
      throw new NotImplementedException("EVM backend scaffolding: GetQuantifierName not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateForeachLoop(
      string tmpVarName, Type collectionElementType,
      IOrigin tok, out ConcreteSyntaxTree collectionWriter, ConcreteSyntaxTree wr) {
      collectionWriter = default;
      throw new NotImplementedException("EVM backend scaffolding: CreateForeachLoop not yet implemented");
    }

    [CanBeNull]
    protected override Action<ConcreteSyntaxTree> GetSubtypeCondition(
      string tmpVarName, Type boundVarType, IOrigin tok, ConcreteSyntaxTree wPreconditions) {
      throw new NotImplementedException("EVM backend scaffolding: GetSubtypeCondition not yet implemented");
    }

    protected override void EmitDowncastVariableAssignment(string boundVarName, Type boundVarType, string tmpVarName,
      Type sourceType, bool introduceBoundVar, IOrigin tok, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitDowncastVariableAssignment not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateForeachIngredientLoop(string boundVarName, int L, string tupleTypeArgs,
      out ConcreteSyntaxTree collectionWriter, ConcreteSyntaxTree wr) {
      collectionWriter = default;
      throw new NotImplementedException("EVM backend scaffolding: CreateForeachIngredientLoop not yet implemented");
    }

    protected override void EmitNew(Type type, IOrigin tok, CallStmt initCall /*?*/, ConcreteSyntaxTree wr,
      ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitNew not yet implemented");
    }

    protected override void EmitNewArray(Type elementType, IOrigin tok, List<string> dimensions,
      bool mustInitialize, [CanBeNull] string exampleElement, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitNewArray not yet implemented");
    }

    protected override void EmitLiteralExpr(ConcreteSyntaxTree wr, LiteralExpr e) {
      throw new NotImplementedException("EVM backend scaffolding: EmitLiteralExpr not yet implemented");
    }

    protected override void EmitStringLiteral(string str, bool isVerbatim, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitStringLiteral not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitBitvectorTruncation(BitvectorType bvType, [CanBeNull] NativeType nativeType,
      bool surroundByUnchecked, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitBitvectorTruncation not yet implemented");
    }

    protected override void EmitRotate(Expression e0, Expression e1, bool isRotateLeft, ConcreteSyntaxTree wr,
      bool inLetExprBody, ConcreteSyntaxTree wStmts, FCE_Arg_Translator tr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitRotate not yet implemented");
    }

    protected override void EmitEmptyTupleList(string tupleTypeArgs, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitEmptyTupleList not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitAddTupleToList(string ingredients, string tupleTypeArgs, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitAddTupleToList not yet implemented");
    }

    protected override void EmitTupleSelect(string prefix, int i, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitTupleSelect not yet implemented");
    }

    protected override string FullTypeName(UserDefinedType udt, MemberDecl/*?*/ member = null) {
      throw new NotImplementedException("EVM backend scaffolding: FullTypeName not yet implemented");
    }

    protected override void EmitThis(ConcreteSyntaxTree wr, bool callToInheritedMember = false) {
      throw new NotImplementedException("EVM backend scaffolding: EmitThis not yet implemented");
    }

    protected override void EmitDatatypeValue(DatatypeValue dtv, string typeDescriptorArguments, string arguments, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitDatatypeValue not yet implemented");
    }

    protected override void GetSpecialFieldInfo(SpecialField.ID id, object idParam, Type receiverType,
      out string compiledName, out string preString, out string postString) {
      compiledName = default;
      preString = default;
      postString = default;
      throw new NotImplementedException("EVM backend scaffolding: GetSpecialFieldInfo not yet implemented");
    }

    protected override ILvalue EmitMemberSelect(Action<ConcreteSyntaxTree> obj, Type objType, MemberDecl member,
      List<TypeArgumentInstantiation> typeArgs, Dictionary<TypeParameter, Type> typeMap, Type expectedType,
      string/*?*/ additionalCustomParameter = null, bool internalAccess = false) {
      throw new NotImplementedException("EVM backend scaffolding: EmitMemberSelect not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitArraySelect(List<Action<ConcreteSyntaxTree>> indices, Type elmtType, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitArraySelect not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitArraySelect(List<Expression> indices, Type elmtType, bool inLetExprBody,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitArraySelect not yet implemented");
    }

    protected override void EmitExprAsNativeInt(Expression expr, bool inLetExprBody, ConcreteSyntaxTree wr,
      ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitExprAsNativeInt not yet implemented");
    }

    protected override void EmitIndexCollectionSelect(Expression source, Expression index, bool inLetExprBody,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIndexCollectionSelect not yet implemented");
    }

    protected override void EmitIndexCollectionUpdate(Expression source, Expression index, Expression value,
      CollectionType resultCollectionType, bool inLetExprBody, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIndexCollectionUpdate not yet implemented");
    }

    protected override void EmitSeqSelectRange(Expression source, Expression lo /*?*/, Expression hi /*?*/,
      bool fromArray, bool inLetExprBody, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitSeqSelectRange not yet implemented");
    }

    protected override void EmitSeqConstructionExpr(SeqConstructionExpr expr, bool inLetExprBody, ConcreteSyntaxTree wr,
      ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitSeqConstructionExpr not yet implemented");
    }

    protected override void EmitMultiSetFormingExpr(MultiSetFormingExpr expr, bool inLetExprBody, ConcreteSyntaxTree wr,
      ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitMultiSetFormingExpr not yet implemented");
    }

    protected override void EmitApplyExpr(Type functionType, IOrigin tok, Expression function,
      List<Expression> arguments, bool inLetExprBody, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitApplyExpr not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitBetaRedex(List<string> boundVars, List<Expression> arguments,
      List<Type> boundTypes, Type resultType, IOrigin resultTok, bool inLetExprBody, ConcreteSyntaxTree wr,
      ref ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitBetaRedex not yet implemented");
    }

    protected override void EmitDestructor(Action<ConcreteSyntaxTree> source, Formal dtor, int formalNonGhostIndex,
      DatatypeCtor ctor, Func<List<Type>> getTypeArgs, Type bvType, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitDestructor not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateLambda(List<Type> inTypes, IOrigin tok, List<string> inNames,
      Type resultType, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts, bool untyped = false) {
      throw new NotImplementedException("EVM backend scaffolding: CreateLambda not yet implemented");
    }

    protected override void CreateIIFE(string bvName, Type bvType, IOrigin bvTok, Type bodyType, IOrigin bodyTok,
      ConcreteSyntaxTree wr, ref ConcreteSyntaxTree wStmts, out ConcreteSyntaxTree wrRhs, out ConcreteSyntaxTree wrBody) {
      wrRhs = default;
      wrBody = default;
      throw new NotImplementedException("EVM backend scaffolding: CreateIIFE not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateIIFE0(Type resultType, IOrigin resultTok, ConcreteSyntaxTree wr,
      ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: CreateIIFE0 not yet implemented");
    }

    protected override ConcreteSyntaxTree CreateIIFE1(int source, Type resultType, IOrigin resultTok, string bvName,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: CreateIIFE1 not yet implemented");
    }

    protected override void EmitUnaryExpr(ResolvedUnaryOp op, Expression expr, bool inLetExprBody,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitUnaryExpr not yet implemented");
    }

    protected override void EmitIsZero(string varName, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIsZero not yet implemented");
    }

    protected override void EmitConversionExpr(Expression fromExpr, Type fromType, Type toType, bool inLetExprBody,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitConversionExpr not yet implemented");
    }

    protected override void EmitTypeTest(string localName, Type fromType, Type toType, IOrigin tok, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitTypeTest not yet implemented");
    }

    protected override void EmitIsIntegerTest(Expression source, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIsIntegerTest not yet implemented");
    }

    protected override void EmitIsUnicodeScalarValueTest(Expression source, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIsUnicodeScalarValueTest not yet implemented");
    }

    protected override void EmitIsInIntegerRange(Expression source, BigInteger lo, BigInteger hi, ConcreteSyntaxTree wr,
      ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitIsInIntegerRange not yet implemented");
    }

    protected override void EmitCollectionDisplay(CollectionType ct, IOrigin tok, List<Expression> elements,
      bool inLetExprBody, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitCollectionDisplay not yet implemented");
    }

    protected override void EmitMapDisplay(MapType mt, IOrigin tok, List<MapDisplayEntry> elements, bool inLetExprBody,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitMapDisplay not yet implemented");
    }

    protected override void EmitSetBuilder_New(ConcreteSyntaxTree wr, SetComprehension e, string collectionName) {
      throw new NotImplementedException("EVM backend scaffolding: EmitSetBuilder_New not yet implemented");
    }

    protected override void EmitMapBuilder_New(ConcreteSyntaxTree wr, MapComprehension e, string collectionName) {
      throw new NotImplementedException("EVM backend scaffolding: EmitMapBuilder_New not yet implemented");
    }

    protected override void EmitSetBuilder_Add(CollectionType ct, string collName, Expression elmt, bool inLetExprBody,
      ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitSetBuilder_Add not yet implemented");
    }

    protected override ConcreteSyntaxTree EmitMapBuilder_Add(MapType mt, IOrigin tok, string collName, Expression term,
      bool inLetExprBody, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitMapBuilder_Add not yet implemented");
    }

    protected override void GetCollectionBuilder_Build(CollectionType ct, IOrigin tok, string collName,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmt) {
      throw new NotImplementedException("EVM backend scaffolding: GetCollectionBuilder_Build not yet implemented");
    }

    protected override void EmitSingleValueGenerator(Expression e, bool inLetExprBody, string type,
      ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) {
      throw new NotImplementedException("EVM backend scaffolding: EmitSingleValueGenerator not yet implemented");
    }

    protected override void EmitHaltRecoveryStmt(Statement body, string haltMessageVarName, Statement recoveryBody, ConcreteSyntaxTree wr) {
      throw new NotImplementedException("EVM backend scaffolding: EmitHaltRecoveryStmt not yet implemented");
    }

    // -----------------------------------------------------------------------
    //  EvmClassWriter: assembles the Huff representation of one Dafny class.
    //
    //  Emission layout (top-down inside the parent writer):
    //     [constantsSection]   // one `#define constant <NAME>_SLOT = 0x..`
    //     [methodsSection]     // one `#define macro <NAME>()` per method
    //     [dispatcher]         // final `#define macro MAIN()` with selector
    //                          //   jumps, written in Finish()
    // -----------------------------------------------------------------------
    private class EvmClassWriter : IClassWriter {
      private readonly EvmCodeGenerator parent;
      private readonly string className;
      private readonly ConcreteSyntaxTree wr;
      private readonly ConcreteSyntaxTree constantsSection;
      private readonly ConcreteSyntaxTree methodsSection;
      private readonly List<string> macroNames = new();
      private int nextSlot;

      public EvmClassWriter(EvmCodeGenerator parent, string className, ConcreteSyntaxTree wr) {
        this.parent = parent;
        this.className = className;
        this.wr = wr;
        // Reserve two in-order placeholders so DeclareField / CreateMethod
        // can write into them regardless of the order the base class visits
        // class members. MAIN() is appended directly to `wr` in Finish().
        this.constantsSection = wr.Fork();
        wr.WriteLine();
        this.methodsSection = wr.Fork();
        wr.WriteLine();
      }

      public void DeclareField(string name, TopLevelDecl enclosingDecl, bool isStatic, bool isConst,
          Type type, IOrigin tok, string rhs, Field /*?*/ field) {
        var slotName = parent.PublicIdProtect(name).ToUpperInvariant() + "_SLOT";
        constantsSection.WriteLine($"#define constant {slotName} = 0x{nextSlot:x2}");
        nextSlot++;
      }

      public ConcreteSyntaxTree CreateMethod(MethodOrConstructor m, List<TypeArgumentInstantiation> typeArgs,
          bool createBody, bool forBodyInheritance, bool lookasideBody) {
        var macroName = parent.PublicIdProtect(m.Name).ToUpperInvariant();
        macroNames.Add(macroName);
        methodsSection.WriteLine($"#define macro {macroName}() = takes(0) returns(0) {{");
        var body = methodsSection.Fork();
        methodsSection.WriteLine("}");
        methodsSection.WriteLine();
        if (!createBody) {
          body.WriteLine("    0x00 0x00 revert   // method body not supplied (abstract)");
          return null;
        }
        // The base class will fill `body` by invoking our Emit* overrides.
        // Those are still stubs, so this is the current frontier.
        return body;
      }

      public ConcreteSyntaxTree CreateFunction(string name, List<TypeArgumentInstantiation> typeArgs,
          List<Formal> formals, Type resultType, IOrigin tok, bool isStatic, bool createBody,
          MemberDecl member, bool forBodyInheritance, bool lookasideBody) {
        // Dafny functions and methods both lower to Huff macros in the MVP.
        var macroName = parent.PublicIdProtect(name).ToUpperInvariant();
        macroNames.Add(macroName);
        methodsSection.WriteLine($"#define macro {macroName}() = takes(0) returns(0) {{");
        var body = methodsSection.Fork();
        methodsSection.WriteLine("}");
        methodsSection.WriteLine();
        return createBody ? body : null;
      }

      public void Finish() {
        wr.WriteLine("/* --------- Dispatcher --------- */");
        wr.WriteLine("#define macro MAIN() = takes(0) returns(0) {");
        wr.WriteLine("    0x00 calldataload 0xe0 shr          // 4-byte function selector");
        foreach (var name in macroNames) {
          var sig = $"{name.ToLowerInvariant()}()";
          wr.WriteLine($"    dup1 __FUNC_SIG(\"{sig}\") eq {name.ToLowerInvariant()}_jump jumpi");
        }
        wr.WriteLine("    0x00 0x00 revert                    // unknown selector");
        foreach (var name in macroNames) {
          wr.WriteLine($"    {name.ToLowerInvariant()}_jump: {name}()");
        }
        wr.WriteLine("}");
      }

      public ConcreteSyntaxTree SynthesizeMethod(Method m, List<TypeArgumentInstantiation> typeArgs,
          bool createBody, bool forBodyInheritance, bool lookasideBody) {
        throw new UnsupportedFeatureException(m.Origin, Feature.MethodSynthesis);
      }

      public ConcreteSyntaxTree CreateGetter(string name, TopLevelDecl enclosingDecl, Type resultType, IOrigin tok,
          bool isStatic, bool isConst, bool createBody, MemberDecl /*?*/ member, bool forBodyInheritance) {
        throw new NotImplementedException(
          "EVM backend: standalone getters not yet implemented (field reads should go via SLOAD)");
      }

      public ConcreteSyntaxTree CreateGetterSetter(string name, Type resultType, IOrigin tok, bool createBody,
          MemberDecl /*?*/ member, out ConcreteSyntaxTree setterWriter, bool forBodyInheritance) {
        setterWriter = null;
        throw new NotImplementedException("EVM backend: getter/setters not yet implemented");
      }

      public void InitializeField(Field field, Type instantiatedFieldType, TopLevelDeclWithMembers enclosingClass) {
        throw new NotImplementedException("EVM backend: inherited-field initialization not yet implemented");
      }

      public ConcreteSyntaxTree ErrorWriter() => wr;
    }
  }
}
